# Generate by https://metrics.lecoq.io/
# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Github Metrics
on:
  # Schedule updates (every monday)
  schedule: [{cron: "0 0 * * MON"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xszhu522
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          committer_branch: github-workflow-output
          filename: github-metrics/github-metrics.*
